### ISSUE TITLE
Дієслівна лема для дієприслівників

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#15]
Йдеться не про заміну леми, а про додавання тегу.
Потрібна для MTE, але і просто корисна інфа. Буде треба для pymorphy.

**Comment by arysin** [comment]
Не зрозумів, про який тег йдеться?

**Comment by msklvsk** [comment]
якийсь типу <code>читаючи … derived-from-читати</code>
Не горить поки, але чому б не обговорити.

**Comment by mariana-scorp** [comment]
Можна, в принципі. Я не проти. Якщо я правильно пам'ятаю, то в МТЕ і для дієприкметників лема дієслова стоїть, чи не так?

**Comment by msklvsk** [comment]
Саме так, того й іш’ю. Але взагалі це частковий випадок зв’язків між лемами. Наприклад, добре мати інфу про дієслово і для дієприкметника. Туди ж і зв’язки між порівняльними формами. Тож, щоб не марнувати час на костилі, це може зачекати на комплексне вирішення зв’язками між лемами.

**Comment by mariana-scorp** [comment]
Зв'язки між порівняльними формами прикметників та прислівників є, але лежать вони поза межами словника. Загалом, думаю, це непогана ідея подавати таку інформацію, наприклад, до початкової форми. Я порушу це питання сьогодні на розмові з командою.

**Comment by msklvsk** [comment]
> лежать вони поза межами словника

а де?

> Я порушу це питання сьогодні на розмові з командою.

Скажи, що це для пайморфі, щоб можна було зліплювати величезну лексему і подорожувати формами. Приклад, де це вже зроблене — словник OpenCorpora того ж пайморфі.
(Але мені ця фіча не горить.)

**Comment by mariana-scorp** [comment]
Міша Коробов з пайморфі вже нас про це питав, але сказав, що поки можна обійтись, тому ми зв'язуванням і не займались.

**Comment by arysin** [comment]
Ця інформація в словнику є, всі дієприслівники мають лемою дієслово. На виході expandForRules так і дає, expandForCorp вмикає опцію lemmaForTags=advp і там advp стає окремою лемою.
