### ISSUE TITLE
Треба выправити назву скрипта convert_from_sell_uk.sh

### ISSUE THREAD

**Issue by Andygol** [arysin/dict_uk#17]
скрипт [convert_from_sell_uk.sh](https://github.com/arysin/dict_uk/blob/master/bin/convert_from_sell_uk.sh) повинен називатись `convert_from_spell_uk.sh`, наскільки я зрощумів

**Comment by arysin** [comment]
Гмм, sell_uk напвне не дуже гарна назва :)
Дякую, виправлено.
