### ISSUE TITLE
Initiate and approach dic into t9 databases

### ISSUE THREAD

**Issue by podarok** [arysin/dict_uk#19]
We should inject vocabulary into modern operation systems like
- Android
- iOs

Also we need to take care about aspell, ispell libraries and basic libs like timezone (change kiev to kyiv) and others

**Comment by arysin** [comment]
Issue for Android has been filed a bit ago
https://code.google.com/p/android/issues/detail?id=78323
spell-uk project (that dict_uk is based on) has been taking care of ispell,
aspell, hunspell and thus Firefox and LibreOffice.org since at least 2000

**Comment by podarok** [comment]
@arysin thanks for the input, I've voted for android as well

**Comment by arysin** [comment]
iOS is quite proprietary and closed so I am not sure this project can help much. 
Changing timezones and city names would be outside of this project scope,
