### ISSUE TITLE
Кличний для усіх

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#29]
Доле noun:inanim:f:v_kly моя, ти де?

**Comment by mariana-scorp** [comment]
Так, у нас на це окрема задача в Асані висить. Треба якось добратись.

**Comment by mariana-scorp** [comment]
@msklvsk, ми в процесі.

**Comment by msklvsk** [comment]
Помітив кличний в питальних займенниках _котрий_, _який_. Чи має сенс?

**Comment by arysin** [comment]
Загальна робота з кличним в принципі завершена. Декілька проблем винесено в окремі питання.
