### ISSUE TITLE
Додати нестягнені форми прикметників

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#3]
- Чи можна вигенерувати програмно?
- Як не мати їх для LT? Прапорець expand_all.py?

**Comment by msklvsk** [comment]
Виношу з пошти питання Андрія:
> можливо варто додавати нестягнені форми лише для кількісних (напр., тих що мають порівняльні форми)? Бо щось так якщо для всіх то забагато виходить там де не треба (напр. абельованая тощо).

Тут або або або: або не мати нестягнені, або виловлювати прикметники для яких вони мають бути (як розрізнити вечірнюю і абельованою?) або мати “забагато”.

Які практичні аргументи проти “мати забагато”? (не забуваймо є --uncontr)

**Comment by msklvsk** [comment]
Жіночі прикметникові прізвища теж дістали нестягнену. Не знаю де правильно їх фільтрувати щоб не в <code>post_process()</code>.

**Comment by arysin** [comment]
вилучив форми з uncontr з відприкметникових іменників
