### ISSUE TITLE
Трактування як і прикметника, і дієприкметника: несумісність

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#32]
Є <code>прибитий adj</code> і <code>прибитий adjp</code>, але тільки <code>драний adjp</code>. Несумісність гірша за неповність трактування.

**Comment by vstarko** [comment]
Слова, які формально є adjp, дістають омонім adj, якщо надаються до ступенювання. В цьому випадку "прибитіший" існує, а "драніший" - ні. І таких випадків багато.

**Comment by msklvsk** [comment]
(з СУМа)
Вивели Марину в драній рядняній сорочці з зав’язаними на спині рукавами.
Дід Ялисей жив самотньо в старій драній хаті аж на краю села.

Нехай не в першому, а у другому реченні хату ніхто ж не драв. Це якщо думати дієслівністю.
Якщо думати ступеневістю, то чого качечці можна бути прибитішою, а сорочка одна драна, а друга ще дранішою не буває? — хіба не розмито?

**Comment by vstarko** [comment]
Ад’єктивізація має різні ступені. Ми йдемо суто за формальним критерієм: вводимо омоніми до словника, коли є відмінності в словозміні або, щодо (діє)прикметників, у ступенюванні. Якщо знайдеться текст, де буде "драніший" чи "найдраніший", - додамо омонім adj.

**Comment by msklvsk** [comment]
(заради естетики змінімо слово на _читаний_, якого теж нема як прикметника; приклад у реченні: “Забужко _читаніша_ від Станіславського феномену докупи взятого”)

За таким протоколом щоразу, як трапляється, наприклад, _читаніший_, ми маємо перебрати усі трапляння _читаний_ у руками розміченому корпусі, бо ми тепер знаємо, що це слово може бути ще й <code>adj</code>, і не знаємо чи там, де ми його уже позначили як <code>adjp</code> (бо вибору не було), воно насправді не <code>adj</code> — bummer! А далі, що як ступінь для такого прикметника взагалі не трапиться? Ви ж не надаєте словам <code>&adj</code> як хак аби описати ступінь — вони просто є <code>adj</code>! У наших тестах анотатор позначив _драний_ як <інше> “бо там не було опції прикметника”.

Я розумію, що це заради збереження чистоти словника, але так втрачається функція _граматичного, для NLP_ словника: подати усі можливі варіанти розбору слова, хай навіть рідкісні. Як щодо того, щоб зберегти чистоту — частотністю, не вилученням слова зі словника взагалі. Якщо треба, можна ігнорувати слова з частотністю нуль, базованою на корпусі, але тримати їх для _створення_ корпусу, особливо спочатку, щоб їх можна було “вибрати”.

Теж саме для нестягненої, і кличного з https://github.com/arysin/dict_uk/issues/29, якого чому б не додати і для неістот, і для множини: і для гір, і зір, і міст, та й, нехай, чашок. Всі ці рядки омонімії муляють психологічно, але лише психологічно. З часом до слів поначеплюється з корпусів ще купа омонімії, яку на потребу доведеться все одно фільтрувати — частотністю.

**Comment by arysin** [comment]
Проблема така є, але розписувати всі потенційні випадки має дві проблеми:
1) це величезна робота
2) вводиться купа омонімії
Оскільки словник орієнтується на практичний вжиток, то думаю варто вводити лише випадкі, які дійсно можуть зустрічатися. Драніший дійсно тре додати як прикметник, але по одному слову то буде дуже довго. Пропоную скласти список всіх випадків, де дійсно не вистачає &adj і додати їх в словник гамузом.

**Comment by mariana-scorp** [comment]
@msklvsk, ми поки не матимемо ресурсів перелопатити всі дієприкметники і визначити, де треба вивести прикметники окремо. Якщо у вас будуть ресурси на це, то ми не проти.

**Comment by vstarko** [comment]
1. Введення купи прикметників-омонімів до adjp може створювати нові проблеми. В деяких випадках буде неможливо (в принципі!) усунути омонімію: наприклад, «Забужко читана.» - це вже adj чи ще adjp? 
2. Є потреба розрізняти рівні аналізу: морфаналіз - поділ на морфологічні (словозмінні) класи; рівень речення (синтаксичний?) - функція слова в реченні (завідуючий - adjp на рівні морфаналізу, але може бути noun на рівні речення). В морфаналізі легше й доцільніше, я вважаю, дотримуватися формальних класів. 
3. Згоден, що це ще проблема/завдання на майбутнє.

**Comment by mariana-scorp** [comment]
@msklvsk, дієприкметники та прикметники тепер в одному класі. Я так розумію, це завдання вже неактуальне?

**Comment by msklvsk** [comment]
ага, проблему вирішено
