### ISSUE TITLE
‘більший’ до ‘великий’ не лематизується, а ‘більш’ до ‘багато’ — так

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#33]
‘краще’ ж взагалі немає як прислівника. Усистемнімо?

**Comment by mariana-scorp** [comment]
@arysin, це до тебе)

**Comment by arysin** [comment]
більший великий adj:m:v_naz:compr
більший великий adj:m:v_zna:rinanim:compr
більш багато adv:compr

лишилося лише додати "краще"
