### ISSUE TITLE
для _себе_ приписані роди (треба?), але нема жіночого

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#36]
<pre>
себе noun:m:v_rod:&pron:refl
  собі noun:m:v_dav:&pron:refl
  себе noun:m:v_zna:&pron:refl
  собою noun:m:v_oru:&pron:refl
  собі noun:m:v_mis:&pron:refl
  себе noun:n:v_rod:&pron:refl
  собі noun:n:v_dav:&pron:refl
  себе noun:n:v_zna:&pron:refl
  собою noun:n:v_oru:&pron:refl
  собі noun:n:v_mis:&pron:refl
</pre>

**Comment by mariana-scorp** [comment]
@Olvija, прокоментуй, будь ласка, і внеси зміни, якщо треба.

**Comment by Olvija** [comment]
добре
