### ISSUE TITLE
_здатен_ прикметник, а _повинен_ predic

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#37]
<code>їстоньки predic</code>, а <code>питоньки verb:imperf:inf:dimin</code> та інші суперечності. За яким принципом слово є предиком?

**Comment by mariana-scorp** [comment]
Це, звісно, помилка. Я гляну.

**Comment by arysin** [comment]
В LT є правило: predic + verb не в початковій формі є помилкою. Це правило перестало працювати для «повинен»:

Message: Дієслово після присудкового слова має йти інфінітивом: 'втручатись', 'втручатися'
«Ніхто не повинен втручається у тренувальний процес»..

**Comment by msklvsk** [comment]
_тринь-бринь_ + verb не в початковій формі теж є помилкою?

**Comment by mariana-scorp** [comment]
@arysin, а як тоді працюють інші форми? "Повинна", "повинні", "здатна", "здатні" + не початкова форма? Може, модальні слова вибрати, а не тег predic використовувати?

**Comment by arysin** [comment]
@mariana-scorp Гмм, логічно, підкоригую логіку.
