### ISSUE TITLE
дублювання _щонайменше_ та інших

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#38]
Є
<pre>мало adv:compb
  менш adv:compr
  менше adv:compr
  найменш adv:super
  найменше adv:super
  щонайменш adv:super
  якнайменш adv:super
  <b>щонайменше adv:super</b></pre>
А є <code>щонайменше adv:super</code > окремою лемою. Те ж з іншими.

**Comment by mariana-scorp** [comment]
Загальна логіка така, що порівняльні форми йдуть у словник окремими лемами. Я бачу, що таке дублювання є лише для слів "багато", "високо" та "мало", тобто для неправильних. @arysin, це бага?
