### ISSUE TITLE
Другий рід для іменників спільного роду

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#4]
- Треба його власне проставити в сирцях.
- Як його виводити? окремою лемою?

**Comment by arysin** [comment]
треба ставити :+m, :+f, :+n в словнику, я проставив для іменників, які швидко знайшов

**Comment by msklvsk** [comment]
35fc1c403e79d1ac04e74371387eada4e5880f25 додало ще ~240. Ще лишається туду: взяти закінчення наявних іменників спільного роду і пробігтися по base.lst, можна знайти ще. Також на r2u можна пошукати “(общ.)”. Але це малий пріорітет.

**Comment by arysin** [comment]
Я пройшовся по спільному роду з r2u.org.ua і оновив словник. Думаю, можна вважати це питання закритим.
