### ISSUE TITLE
_кожен_ без :&pron

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#41]
<pre>
кожний adj:m:v_naz:&pron:def
  кожного adj:m:v_rod:&pron:def
  …
  кожен adj:m:v_naz:short
  кожен adj:m:v_zna:short
</pre>

**Comment by mariana-scorp** [comment]
@Olvija прокоментуй, будь ласка, і внеси зміни, якщо треба.

**Comment by Olvija** [comment]
добре, погляну

**Comment by msklvsk** [comment]
виправлено в 1b4941cdbd006fba6d1e24a5d559a64ba3ad455b
