### ISSUE TITLE
часу :v_mis

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#43]
<code>жокею :v_mis</code>, <code>в’їзду :v_mis</code>
Так правильно чи глюк?

**Comment by arysin** [comment]
Правильно, див. http://www.mova.info/grmasl.aspx

**Comment by msklvsk** [comment]
є в планах їх розрізняти? (і прийменники відповідно до різних місцевих прив’язувати)

**Comment by arysin** [comment]
Теоретично треба було б, але наразі не на порядку денному :)

4 січня 2016 р. о 12:33 msklvsk <notifications@github.com> написав:

**Comment by msklvsk** [comment]
Коциба:
> u polskij taki konstruktsiji traktujutsia jak davalnyj (ne te shchob na nyh treba rivniatysia, prosto jak pryklad alternatyvnoho bachennia) -- forma ta sama, navishcho tse semantyzuvaty

Цікаво. Я б навіть сказав що так краще ніж зараз, бо зараз виходять несумісності типу “при штабу”, які словник вважає валідними. Але декілька місцевих, можливо, найкраще.

**Comment by mariana-scorp** [comment]
Я думаю, роль словника - описати всі варіанти. Компонування прийменника з іменникомчи будь-яке інше компонування - це вже поза сферою відповідальності словника. `rv_*` тегів цілком достатньо.

**Comment by msklvsk** [comment]
Зараз тег <code>:rv_</code> вимагає будь-якого місцевого (з трьох), а насправді вимагається конкретний однин місцевий. Це the сфера словника. І в тій табличці на mova.info якраз конктетний місцевий і вказується.

**Comment by msklvsk** [comment]
зараз словник дає менше інфи, більше невизначеності ніж навіть у поляків з їхнім трактуванням як давального

**Comment by mariana-scorp** [comment]
Я вважаю, що це вже робота морфаналізатора, а не словника. Ці питання буде простіше вирішити статистично, ніж вносити всі варіанти компонування для кожного прийменника-іменника.

**Comment by msklvsk** [comment]
Ніде про варіанти конкретного компонування не йдеться. Коли додадуться три знахідні (і вище Андрій каже що добре було-б), то прийменники зможуть вимагати когось з них трьох, і _при_ не вимагатиме того знахідного, що _штабу_, а вимагатиме того, що _штабі_. Це конкретизація інфи <code>rv_</code>, типу точніший <code>rv_</code>.

**Comment by mariana-scorp** [comment]
Ага, може я не так зрозуміла. Питання в тому, щоб `rv_mis` розбити на три різні випадки, наприклад? Але чи це просто буде гамузом для всіх іменників зробити?

**Comment by msklvsk** [comment]
> Питання в тому, щоб rv_mis розбити на три різні випадки, наприклад?

Саме так.

>  Але чи це просто буде гамузом для всіх іменників зробити?

Перебір же не по іменниках, а по займенниках треба буде робити. Нехай три дні роботи (залюбки зробимо), але це не ноу-хау: у інших тагсетах/корпусах/словниках так роблять, і ми зможемо.

**Comment by mariana-scorp** [comment]
По займенниках? Чи по прийменниках? Знову не розумію.

**Comment by msklvsk** [comment]
прийменниках, звичайно, виправив

**Comment by mariana-scorp** [comment]
Добре. Тепер зрозуміло. Виглядає на гарне доповнення. І для LT знадобиться.

**Comment by arysin** [comment]
А чи всі v_mis треба розбивати на v_mi1/v_mi2/v_mi3 чи лише якісь з них?

17 січня 2016 р. о 11:56 mariana-scorp <notifications@github.com> написав:

**Comment by natko5** [comment]
Думаю. що далеко не всі, але це найкраще визначати експериментально, біграми подивитися. (Знаю, що це трохи замкнуте коло.)

**Comment by msklvsk** [comment]
> А чи всі v_mis треба розбивати на v_mi1/v_mi2/v_mi3 чи лише якісь з них?

Типу чи в усіх парадигмах?
Чи “в тих парадигмах, де `v_mis` один, чи треба вказувати кортим з `v_mi1/v_mi2/v_mi3` він є”?

**Comment by arysin** [comment]
Ну скажімо у жіночому такого розбиття немає: вага - єдиний м.в. вазі, тобто
схоже це лише тре для ч./с. р.?
Тобто можливо мати v_mis для всіх, а там де є розбиття зробити за аналогом
v_zna + ranim/rinanim: v_mis + rprep_po, rpep_na або щось в такому дусі...

2 лютого 2016 р. о 11:30 msklvsk <notifications@github.com> написав:

**Comment by msklvsk** [comment]
>Тобто можливо мати v_mis для всіх, а там де є розбиття зробити за аналогом
v_zna + ranim/rinanim: v_mis + rprep_po, rpep_na або щось в такому дусі...

Так і хотілося б. Тільки там же буде по декілька прийменників на відмінок, можна навіть `:v_mis:v_mi1`.
