### ISSUE TITLE
нові інформативні теги: його/нього і компанія

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#44]
Подібно до :ranim, корисна інфа яку легко додати, щось типу <code>:rprep</code>. Здається, знадобиться в LT.
Зараз жодного розрізнення:
<pre>
їх  noun:p:v_rod:&pron:pers:3
них noun:p:v_rod:&pron:pers:3
</pre>

**Comment by mariana-scorp** [comment]
Це лише в особових займенниках таке є, правильно? Можна додати. `rprep` буде ок - requires a preposition)

**Comment by natko5** [comment]
Наскільки я орієнтуюся, то тільки особові. Тільки в деяких діалектах з прийменниками "голі" форми вживають, наприклад на Волині можна почути "для її", "на його". Тому це не рестриктивне.

**Comment by mariana-scorp** [comment]
@msklvsk, команда вирішила, що це зайве. Якщо вам цей тег потрібен, мабуть додайте вже у вашій версії. :)

**Comment by msklvsk** [comment]
@mariana-scorp, що вас засмутило в цьому тегу? бо може і у форку не треба додавати…

**Comment by natko5** [comment]
Богдане, а звідки ідея його додати взагалі? Такий таг є тільки у поляків, наскільки я орієнтуюся. Він не має граматичної природи, ближчий скоріше до фонетичної варіативності. Суттєвим може бути на рівні генерування мови, а не аналізу, може для деяких евристик при уоднозначненні -- але все це можна заступити правилами типу "(не)починається з приголосної". Мені здається, він у цьому місці штучний.

**Comment by msklvsk** [comment]
Це пішло від скрипта який шукав омонімію навпаки: де в лексемі різні слова мають однакові теги, бо може це значить що тегами не описана якась граматична різниця (як було з `:ranim`). Потім побачив цей тег у поляків, закинув на розгляд, через чотири місяці отримав відповідь.
