### ISSUE TITLE
нові інформативні теги: ввічлива форма

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#46]
Подібно до https://github.com/arysin/dict_uk/issues/44, корисна інфа, легко додати, розрізнятиме 
<pre>
зробіть verb:perf:impr:s:2
зроби   verb:perf:impr:s:2
</pre>
особливо коли виправиться https://github.com/arysin/dict_uk/issues/45.

**Comment by arysin** [comment]
Я не впевнений чи граматично є користь для розрізняння множини і ввічливої форми однини. Я б сказав, що це буде зайва омонімія.

**Comment by msklvsk** [comment]
Я і не кажу про розрізняння множини і ввічливої форми однини. Я кажу про розрізняння двох форм <code>impr:s:2</code>. Жодної омонімії, навпаки зняття тегової омонімії, додавання інформації.

**Comment by msklvsk** [comment]
Тепер зрозумів, що однина для _зробіть_ це була помилка і ти її пофіксив у #45.

**Comment by msklvsk** [comment]
Треба подумати як тоді зробити можливим пошук ввічливих форм у корпусі…
Наприклад, як прослідкувати звертаня до батьків на ви: коли почало зникати, яка відносна частота.

**Comment by arysin** [comment]
Гаразд, але тут словник надто не допоможе, навіть якщо ми введемо додаткову
омонімію потрібно буде її знімати алгоритмом, тож все навантаження на нього.
Якщо буде потреба і алгоритм тоді можна поміркувати що правити в словнику.

4 січня 2016 р. о 14:16 msklvsk <notifications@github.com> написав:

**Comment by mariana-scorp** [comment]
Не думаю, що це розрізнення варто вносити в словник. Ввічливе "Ви" узгоджується точно так само, як "ви".

**Comment by msklvsk** [comment]
Спробуємо розрізняти це на рівні смислового уоднозначнення, може і вдастся прослідкувати звертання до батьків.
