### ISSUE TITLE
пасти гусей і пасти навколішки — одна лема

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#47]
<pre>
пасти verb:imperf:inf
  пади verb:imperf:impr:s:2
  паси verb:imperf:impr:s:2
  падім verb:imperf:impr:p:1
  пасім verb:imperf:impr:p:1
  падімо verb:imperf:impr:p:1
  пасімо verb:imperf:impr:p:1
  падіть verb:imperf:impr:p:2
  пасіть verb:imperf:impr:p:2
  ⋮
</pre>
Глюк чи ще руки не дійшли до розрізнення за наголосом? Ця штука шкодитиме.

+
відпасти
припасти
підпасти
зади́ха́тися
коли́са́тися
заколи́са́тися
пле́ска́тися
розпле́ска́тися
струменітися ? — там лексема на 51 форму, не можу зрозуміти
о́бі́д

**Comment by arysin** [comment]
Руки не дійшли :), це одне з моїх найприорітетніших завдань:
https://github.com/arysin/dict_uk/blob/master/doc/TODO.txt
* розвести омоніми/омографи тощо
але в цьому випадку словники кажуть, що обидва слова мають однаковий наголос: па́сти

**Comment by msklvsk** [comment]
та і люди кажуть па́сти, навіть на Київщині. я наплутав

**Comment by arysin** [comment]
коли́са́тися, заколи́са́тися з різними наголосами в словниках не знайшов
розпле́ска́тися, струменітися мають паралельне відмінювання:
розпле́щеться, розплеска́ється та струмени́ться, струмені́ється
