### ISSUE TITLE
немає розрізнення ні́ким і ніки́м (немає категорії emphatic)

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#48]
Зацініть різницю: там тобі не знати ніко́го / там тобі не знати ні́кого (всі відомі).

Це ті, що в MTE emphatic. Цінна інфа, а не просто формальність для звідності в MTE. Можна не вносити окрему категорію (бо всі emphatic є negative), а лиш додати позначку, але тут треба подумати: вони зовсім різні, у них зовсім різний синтаксис: емфатичне включає в себе й присудок, тобто _ні́ким_ це скорочення до _немає ким_. ~~Їх всього два: _нікого_ і _нічого_ з відмінками.~~

@mariana-scorp @vstarko @Olvija

**Comment by mariana-scorp** [comment]
Хмм... Good point. Якщо їх всього два і вони по-різному вживаються, варто додати.

**Comment by mariana-scorp** [comment]
@msklvsk, там їх не два, щось ти мене баламутиш :)
Ще є нІкуди, нІде, нІзвідки, нІколи і нІяк. Обговорюємо.

**Comment by msklvsk** [comment]
точно, а в уліфі наґрепалось тільки два

**Comment by arysin** [comment]
Там би ще в коментарях було б варто додати слово з наголосом (там де є наголосові омографи)
