### ISSUE TITLE
Чисто технический момент

### ISSUE THREAD

**Issue by MikeMos** [arysin/dict_uk#49]
В словаре использованы два вида кавычек: парные и непарные. Оправдано ли?

**Comment by arysin** [comment]
Перепрошую, про які лапки йде мова? Сам словник не має лапок. Чи мова про
скрипт в пітоні?

**Comment by MikeMos** [comment]
ніццький /adj    #від "Ніцца" (Франція) 
призовний /adj    # від «призов» 

31 декабря 2015, 02:21:59, от "arysin" < notifications@github.com >: 

Перепрошую, про які лапки йде мова? Сам словник не має лапок. Чи мова про 
скрипт в пітоні?

**Comment by arysin** [comment]
А, це лише коментарі, вони не використовуються на виході. В планах є додати
їх у вихід у візуальному форматі, але вони будуть корисні лише для людини,
тож не має значення які лапки.
