### ISSUE TITLE
додаткова інфа про зворотність ‘свій’ та присвійність ‘чий’ і похідних

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#51]
Пам’ятаєте це з пошти? Ці два займенники є одночасно двох типів. Чи можна додати цю інфу? може через амперсанд. @Olvija

**Comment by Olvija** [comment]
Гаразд, знайду цю інфу в пошті.
Це важлива заувага.
Як додати - це до Андрія.
29 груд. 2015 00:19, користувач "msklvsk" <notifications@github.com>
написав:

**Comment by Olvija** [comment]
потрібно обговорити це в групі

**Comment by mariana-scorp** [comment]
@msklvsk, а дай джерело, де пише, що "свій" є зворотнім? Уся література каже, що в українській мові зворотній лише "себе".

**Comment by mariana-scorp** [comment]
@msklvsk, те саме питання про "чий". Чи можна якісь джерела? Або приклад, де він буде присвійним? До "чий" не можна поставити питання "чий?", бо він вже питальний xD

**Comment by msklvsk** [comment]
> джерело, де пише, що "свій" є зворотнім

УЛІФ в угтазі. Це з тих, що я знаю. Для іншого треба дочекатися Наталі. Суто зворотним є лише _себе_, інші є якогось свого типу, але мають у ознаку зворотності.

Я про зворотність думаю як про фічу, що націлює займенник на того, про кого ти говориш. Типу _Ти любиш себе і своє та я люблю себе і своє_ — слова _себе_ і _своє_ вказують у двох підреченнях на різне, але _Ти любиш її і я люблю її_ — тут _її_ — одна особа. І це якраз інфа для NLP. Те ж саме, до речі, і _сам_, забув про нього. Але я нічого не читав і це просто думки, треба Наталя.

А взагалі, чим тобі ти і твоя чуйка з common sense не джерело? NLP для української це ж не давно усталена штука, очікувано, що ти внесеш щось нове.

**Comment by mariana-scorp** [comment]
@msklvsk, так мені якраз чуття підказує, що "свій" не є зворотнім. Мені чуття каже, що він присвійний.
Не бачу в УЛІФі інформації про зворотність "свого", дай лінку :) (та й УЛІФ - це таке собі джерело, чесно кажучи)

Щодо твого прикладу. _Він любить мене і все моє_ - але "мене" і "моє" живуть в різних видах займенників. _Ти любиш її, і я люблю її_ - як доживемо до розв'язання анафори, поговоримо ;) А що як _Ти любиш її, а я люблю її_ - тут різні _її_. Я лиш сполучник змінила :)

**Comment by msklvsk** [comment]
Тоді лишай/закривай це іш’ю, а ми у форк додамо. Якщо надумаєте — завжди можна з нього взяти назад.

**Comment by mariana-scorp** [comment]
Я не проти додати, як буде аргументоване пояснення :) Може, Наталя щось хорошого скаже?

**Comment by natko5** [comment]
Мені здається, що проблема академічних джерел у тому, що вони намагалися представити семантику зауменників як ортогональну систему. Якщо слово "дівчинка" має сему "молода, мала", то семи "жіночий рід" вона вже мати не може?

**Comment by mariana-scorp** [comment]
Я не зовсім зрозуміла коментар, мені здається.

**Comment by natko5** [comment]
"так мені якраз чуття підказує, що "свій" не є зворотнім. Мені чуття каже, що він присвійний."
Трохи інша аналогія -- якого кольору український прапор - жовтий, синій чи червоний? Перші дві відповіді правильні, але тільки частково. Але якщо ми будемо намагатися знайти відповідь тільки серед тих трьох варіантів, то прийдеться цим і задовільнитися.
"але "мене" і "моє" живуть в різних видах займенників." -- а яка з цим проблема? Тут же мова про семантику, а не синтаксичні категорії.

**Comment by msklvsk** [comment]
@mariana-scorp, знайшов ще одне джерело: http://universaldependencies.org/u/feat/Poss.html
Дивись готову пропозицію: https://github.com/arysin/dict_uk/pull/83

**Comment by msklvsk** [comment]
http://universaldependencies.org/u/feat/PronType.html
>See also the Poss feature that distinguishes normal personal pronouns from possessives. Note that Prs also includes reflexive personal/possessive pronouns (e.g. [cs] se / **svůj**; see the Reflex feature).
