### ISSUE TITLE
стафілокок

### ISSUE THREAD

**Issue by arysin** [arysin/dict_uk#53]
ULIF каже стафілокок — це істота (відмінюється, як тварина)
ГС дає парадигму, що не є ані істотою, ані неістотою (власне як вони й кажуть): там подвійний знахідний множини (як у тварин: =р.в. і =н.в.) і подвійний знахідний однини (=р.в. і =н.в.).
Мені здається, що мати одну лему з такою парадигмою краще, ніж вводити омонімію двох лем anim/inanim. От лише не знаю чи тоді треба для бактерій вводити третю форму «істотності» (bacanim? :))

**Comment by mariana-scorp** [comment]
Дві леми не хочеться взагалі. Треба перевірити, що дасть окремий тег :microbe =)

Хоча :bacanim мені більше подобається :)

**Comment by arysin** [comment]
Я думаю про щось на штиб :bianim, але є деякі проблеми з новою категорією, напр. зараз динамічний тегувальник для слів через дефіс опрацьовує варіант коли anin/inanim обох частин збігаються і потім випадок anim-inanim та inanim-anim, якщо ще буде 3-тя категорія замість 3-х варіантів тре буде знати про 7 (можливо десь можна узагальнити, але я до того що додавання нової категорії не зовсім безплатне).

**Comment by arysin** [comment]
Додано прапорець .<>> для бактерій, який на виході генерує подвійний знахідний як однини так і множити і лема отримує тег :unanim
