### ISSUE TITLE
Не всі :lname дістали :prop

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#74]
`Гайдуцький noun:anim:m:v_naz:lname`
`Ящук noun:anim:f:v_rod:nv:np:lname`

**Comment by msklvsk** [comment]
ще лишилися:
`pcregrep "fname|lname|patr" dict_corp_vis.txt | pcregrep '^((?!prop).)*$'`

**Comment by msklvsk** [comment]
reopen щоб не забути?

**Comment by arysin** [comment]
Здається все.

2016-03-23 19:42 GMT-04:00 msklvsk <notifications@github.com>:
