### ISSUE TITLE
Дубльовані Називний і Знахідний у вусах

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#8]
у згенерованому словнику:
<pre>вуса noun:inanim:p:v_naz:ns
  вуса noun:inanim:p:v_naz  <————
  вусів noun:inanim:p:v_rod:ns
  вусам noun:inanim:p:v_dav:ns
  вуса noun:inanim:p:v_zna:ns
  вуса noun:inanim:p:v_zna  <————
  вусами noun:inanim:p:v_oru:ns
  вусах noun:inanim:p:v_mis:ns</pre>
(може трапляється ще десь)

**Comment by msklvsk** [comment]
схоже
<pre>біга noun:inanim:p:v_naz:bad  <———— без :ns
  біга noun:inanim:p:v_naz:ns
  бігів noun:inanim:p:v_rod:ns
  бігам noun:inanim:p:v_dav:ns
  біга noun:inanim:p:v_zna:bad  <———— без :ns
  біга noun:inanim:p:v_zna:ns
  бігами noun:inanim:p:v_oru:ns
  бігах noun:inanim:p:v_mis:ns</pre>

**Comment by arysin** [comment]
виправлено
