### ISSUE TITLE
Стандартизація: excl → intj

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#89]
Звичним міжнародним терміном для вигука є _Interjection_:

- [UD](http://universaldependencies.org/u/pos/INTJ.html),
- [MT&MTE](http://nl.ijs.si/ME/V4/msd/html/msd.I-uk.html) (всі мови),
- [OpenCorpora](http://opencorpora.org/dict.php?act=gram),
- [Польський національний](http://nkjp.pl/poliqarp/help/ense2.html#x3-30002.1),
- [Чеський](https://ufal.mff.cuni.cz/pdt/Morphology_and_Tagging/Doc/hmptagqr.html#POS),
- [Вікіпедія](https://en.wikipedia.org/wiki/Interjection),
- не знайду де _не_ interjection…

Словник неодмінно буде використовуватися (доповнюватися) славістами зі всього світу.
Пропоную використати таке ж позначення як в UD: `intj`.

**Comment by arysin** [comment]
Має сенс, але вимагає також змін в LT, тож десь ближче до червня зробимо перейменування.
