### ISSUE TITLE
Треба .gitingore’ити виходові файли

### ISSUE THREAD

**Issue by msklvsk** [arysin/dict_uk#9]
Вигенерувані файли заважають при розробці. Не знаю чи їх по одному в ігнор додати, чи патерном, чи в одну папку всіх направити і її ігнорити…

**Comment by msklvsk** [comment]
я мав на увазі генеровані словники, типу dict_corp_vis.txt

**Comment by arysin** [comment]
В мене ігнорує, в тебе ні?

**Comment by msklvsk** [comment]
Ні, вони з’являються прямо в корені. Хіба для них є патерн?:
<pre>**/__pycache__/
**/*.log
**/*.diff
/build/
**/tmp/
out/prev/*
out/*.txt
.*</pre>

**Comment by arysin** [comment]
аа, в мене в скриптах я роблю cd out/ перед генеруванням :)

2015-12-13 2:29 GMT-05:00 msklvsk <notifications@github.com>:
