### ISSUE TITLE
Email розробників

### ISSUE THREAD

**Issue by Maximaximum** [arysin/dict_uk#96]
На жаль, не зміг знайти ліпшого способу вийти з вами на зв'язок, тому пишу тут. Залюбки переніс би спілкування, наприклад, в email.
----
Перш за все, дякую розробникам, що взялися за таку важливу справу!

Хотів би дещо уточнити. Не можу зрозуміти, як користуватися даним словником. Де можна прочитати про формат вихідного файла і як його використовувати?

Скажімо, в мене є потреба поставити певне слово в родовий відмінок. Як це зробити? Є якісь бібліотеки, які вміють працювати з такими файлами?

Буду вдячний за допомогу!

**Comment by arysin** [comment]
В принципі зі словником можна робити дві речі:
1) згенерувати всі можливі словоформи для слів, що вже є в словнику (кроки є на головній: gradle expand і потім повні файли словоформ в теці out/), див. https://github.com/arysin/dict_uk/blob/master/README.md
2) генерувати форми для довільних слів: див. https://github.com/arysin/dict_uk/blob/master/doc/interactive_mode.md; опис прапорців ось тут https://github.com/arysin/dict_uk/blob/master/doc/affix_groups.txt, приклад подання для наявних слів можна глянути тут https://github.com/arysin/dict_uk/blob/master/data/dict/slang.lst

Якщо ще є питання, то моя пошта arysin@gmail.com

**Comment by Maximaximum** [comment]
Щойно написав вам на пошту. Дякую.
